### ISSUE TITLE
Place new alerts at the top of the list

### ISSUE THREAD

**Issue by naxsooley** [chadly/react-bs-notifier#15]
Fresh alerts should appear at the top of the list.

Please make an option to achieve this.

**Comment by chadly** [comment]
This is something you can implement in your application's logic. The `AlertList` simply takes an array of alerts and renders them. When appending to your array, just use `unshift` instead of `push`. See [MDN for more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array).
