### ISSUE TITLE
webpack bloat after require and "addComponentAsRefTo(...): Only a ReactOwner can have refs" error

### ISSUE THREAD

**Issue by ChrisFerrell** [chadly/react-bs-notifier#17]
So I'm using Typescript and since there's no typings files, I use

```js
const Alert = require('react-bs-notifier/lib/alert').default;
```

to get `Alert`. `Alert` works fine, but I need `AlertContainer` because I want it positioned up top-right.

For `AlertContainer` I do:

```js
const AlertContainer = require('react-bs-notifier/lib/container').default
```

Right when I import `AlertContainer`, my webpack bundle goes up from 400k to 1.27 MB and I get an error:

> addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded https://facebook.github.io/react/warnings/refs-must-have-owner.html

It almost seems like webpack is loading a local copy of `React` for some reason. but I can't find it in `node_modules`.

I started googling, and came across callemall/material-ui#2818 which is exactly what is happening with me (specifically, [this comment](https://github.com/callemall/material-ui/issues/2818#issuecomment-175727836)). Some people in that thread are saying its an issue with peer dependencies vs dev dependencies. [This comment](https://github.com/callemall/material-ui/issues/2818#issuecomment-187523400) seems to be the crux of the problem.

My `webpack.config.js` is using externals for `React` and `ReactDom`

```js
externals: {
      "react": "React",
      "react-dom": "ReactDOM"
}
```

and I tried to use an alias for react under resolve in `webpack.config.js` but that didn't help.

Any ideas?

**Comment by chadly** [comment]
Hmm, this package has a dependency on `react-addons-css-transition-group` which, according to that last comment you referenced, seems to be the problem. [It is used here](https://github.com/chadly/react-bs-notifier/blob/master/src/container.jsx#L2) in the `AlertContainer`.

Try externalizing that dependency as well to get your bundle size down.

---

Also, as an aside, rather than reference the files in `lib` directly, you should reference the components from the default export of the package. e.g. instead of this:

``` js
const Alert = require('react-bs-notifier/lib/alert').default;
```

do this:

``` js
const Alert = require('react-bs-notifier').Alert;
const AlertContainer = require('react-bs-notifier').AlertContainer;
const AlertList = require('react-bs-notifier').AlertList;
```

which is the equivalent of:

``` js
import { Alert, AlertContainer, AlertList } from "react-bs-notifier";
```

The individual files in `lib` might get renamed with minor/patch version bumps but the default exports of the package won't change except with a major version bump.
